### PR TITLE
Add generic byte RingBuffer class

### PR DESCRIPTION
**Pull request by facchinm**
- cloned from samd core
- implement addStorage() API to allow static/dynamic size increase

### CODE REVIEW

**Comment by aentinger** [comment]
@facchinm I believe we can close this one? Looks like ancient history :wink:

**Comment by aentinger** [comment]
Obsolete, due to templated [RingBuffer](https://github.com/arduino/ArduinoCore-API/blob/master/api/RingBuffer.h).

**Comment by PaulStoffregen** [comment]
I disagree.  The template does **NOT** solve the need for users to increase the buffer sizes from their Arduino sketches.

This issue is not resolved.  Instead of offering a solution to the need of users to have a larger buffer, the internal private code was changed in a manner which can't be used from Arduino sketches.  The issue is not solved.  It should be reopened.

**Comment by aentinger** [comment]
@PaulStoffregen this was a quite outdated PR with next to no hope to salvage anything from it. The issue you are raising in your [comment](https://github.com/arduino/ArduinoCore-API/pull/8#issuecomment-738733132) is about the capability to configure the size of a ringbuffer to ones liking. If you feel that this is something we should make available I'll invite you to [create an issue](https://github.com/arduino/ArduinoCore-API/issues/new/choose) or point us towards an existing one.

**Comment by aentinger** [comment]
Ah and here it is: https://github.com/arduino/ArduinoCore-API/issues/115.

**Pull request closed without merging**
