### PR TITLE
Split Common.h into separate Wiring headers

### PR DESCRIPTION
**Pull request by kezorm**
Split out all the various function prototypes in Common.h.  Task specific headers make for code that is  easier to read, maintain, and extend.

### CODE REVIEW

**Comment by kezorm** [comment]
Note that the new files are currently lacking copyright blocks.  I'll be glad to add the appropriate block to the files before merge if everyone otherwise agrees to the changes.

**Comment by matthijskooijman** [comment]
Why the "W" prefix on headers? Seems like the wiring-origins are mostly historical, no need to pull that naming convention into this new repo?

Also, it might be interesting to explicitly define if all these filenames are part of the public API (e.g. should people include a single file that includes the rest and is the splitting only an implementation detail, or can each header be separately included? (this is actually relevant even regardless of this PR, of course, but this PR prompted the question for me).

**Comment by kezorm** [comment]
Yes, "W" was historical Wiring naming.  I'm absolutely good with dropping the W.

Personally, I would prefer to see headers included only when needed.  Each header should stand on its own and c/c++ files should only include the headers they need in top down order (see squelart's answer here - https://stackoverflow.com/questions/2762568/c-c-include-header-file-order ).

But, thinking of Arduino sketches, everything gets hidden away from the user.  Easiest way seems like an Arduino.h file at core level and ArduinoAPI.h at api level.  This way, the high level doesn't need to change its call to ArduinoAPI as the underlying API changes and grows over time.  If people want to use ArduinoCore-API outside of Arduino IDE and sketches, they can decide on their own whether to use ArduinoAPI.h or individual headers.  On that note, we should ensure that every header in the API can compile on its own.

**Comment by kezorm** [comment]
Thinking more about naming of headers, it seems like might be a good idea to have consistent prefix or suffix to API file names in order to prevent collision with headers at higher level.  While it is certainly possible to have multiple header files with same name in a project, it can also end up a significant source of confusion.  I think this is mostly why I stuck with the 'W' prefix.  Assuming split out headers, what would `WMath.h` become?  `Math.h` definitely seems a bad idea.  And, with everything hidden behind the single `ArduinoAPI.h` include, the end user won't necessarily know that there's a header named `Digital.h` or `Print.h` or etc.

So, I think it would be a good idea to give every "public" header file a name that is unlikely to be duplicated or confused with anything else.  A consistent prefix (my vote) or suffix on every header file seems like best way...

Of course this topic also extends to .c and .cpp files.  While it's possible (albeit confusing) to have multiple .h files of same name, I don't know of any toolchains that play well with duplicate .c or .cpp filenames.

**Comment by PaulStoffregen** [comment]
There can be a great difference between "best" and most practical, especially when you have a long-established ecosystem of 3rd party code.  In the roughly 50 years of computing history, many have attempted a reorganization such as this, where the only value added is a more orderly & better documented API.  It rarely goes well, unless coupled with the addition of major new features that compel people to invest their precious time to update & adapt.

**Comment by aentinger** [comment]
Thank you @kezorm for your contribution. However, I'll go ahead and follow @PaulStoffregen's reasoning which is why I'm closing this PR.

**Pull request closed without merging**
