### PR TITLE
Extend Arduino API by introducing a function called `digitalToogle`.

### PR DESCRIPTION
**Pull request by tetex7**
I also add a Toggle call for the Digital IO 
and the cla bot got problems

### CODE REVIEW

**Review by per1234 — CHANGES_REQUESTED** [review]
Hi @tetex7. Thanks so much for your pull request!

> the cla bot got problems

I see that you have already signed our Contributor License Agreement (CLA). Unfortunately, the **@[]()CLAassistant** bot has not been able to validate the pull request.

This is caused by the email address used in your local Git settings not being associated with your GitHub account.

You can see the email address that is being used in the commit metadata here:

https://api.github.com/repos/arduino/ArduinoCore-API/commits/10ab4d4415f894a0f0622bb5e042dac04182e846

Please follow these instructions to resolve the issue:

https://docs.github.com/pull-requests/committing-changes-to-your-project/troubleshooting-commits/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

Hopefully the check will automatically pass once that has been done. If not, please comment here and we will investigate.

**Comment by aentinger** [comment]
Hi @tetex7 :coffee: :wave: 

Thank you for your PR.

A desire for `toogle` is one thing but I can say with reasonable certainty that such a wrapper will not become part of the Arduino API for the foreseeable future.

The Arduino API is the lowest common denominator across all Arduino ecosystems and the success of Arduino is based in no small part exactly of that very small API (`pinMode`, `digitalRead`, `digitalWrite,` etc.). There's no question that other and - possibly better- abstractions exist, but the chance of adding a redundant abstraction (i.e. in this case - a new was to access a digital input) is extremely low, to say the least.

Cheers, Alex

**Comment by tetex7** [comment]
@per1234 i removed the C++ wrapper for the IO per request

**Comment by tetex7** [comment]
sorry about the trouble it's my first pull request

**Comment by aentinger** [comment]
So. I probably should have called this sooner, but there's little change that this API will be added to ArduinoCore-API. Unfortunately we do not have yet a set process of how to add anything to the Arduino language (or API) but I feel it's within my purview to close this PR (and ceasing to pretend that it might be considered eventually). If and when such a process is in place I'll be bringing in your API extension request on your behalf, should you not do it yourself.

**Pull request closed without merging**
