### PR TITLE
Added two missing macros to the compatibility pgmspace.h

### PR DESCRIPTION
**Pull request by CamelCaseName**
These two macros were missing so i added them

### CODE REVIEW

**Comment by aentinger** [comment]
Missing in comparison to ... which other file? In which header file have these macros been previously included?

**Comment by CamelCaseName** [comment]
They are in the original avr/pgmspace.h inclouded with all Arduino ide 1.x and 2.x installs for avr boards.

ref: https://www.nongnu.org/avr-libc/user-manual/group__avr__pgmspace.html

**Comment by aentinger** [comment]
The AVR core doesn't use ArduinoCore-API, however I've tested your change with

* ArduinoCore-samd :heavy_check_mark: 
* ArduinoCore-mbed :heavy_check_mark: 
* ArduinoCore-megaavr :heavy_check_mark: 
* ArduinoCore-renesas :heavy_check_mark: 

and I could not find a regression :+1: .

**Review by aentinger — APPROVED** [review]
LGTM :+1:

**Pull request merged**
