### PR TITLE
Bool as return value for logical operations

### PR DESCRIPTION
**Pull request by mcspr**
ref.
https://github.com/esp8266/Arduino/pull/7939

Make sure comments are correct and make it clear to the user that these only return either true or false, and not a numeric value.

### CODE REVIEW

**Review by aentinger — APPROVED** [review]
@facchinm What do you reckon? Any undesirable side-effects you can think of? Looks good to me.

**Comment by per1234** [comment]
It was rolled out to all ESP8266 users in that platform's [3.0.0 release](https://github.com/esp8266/Arduino/releases/tag/3.0.0) 9 days ago and I haven't seen any reports of problems from them. But I'm also not super tuned in to the ESP8266 community.

**Comment by facchinm** [comment]
@aentinger I can't see any undesirable side effect since the usual promotion/demotion automatic rules apply, I'm ok for merging it :wink:

**Comment by aentinger** [comment]
Good to go then. Can't think of any undesirable side-effects myself.

**Pull request merged**
