### PR TITLE
Fix #217 issue with compiling with newer compiler

### PR DESCRIPTION
**Pull request by jboynes**
See comment on #217 about problem compiling tests on desktop (specifically with clang 15.0.0)

### CODE REVIEW

**Review by aentinger — COMMENTED** [review]
This may be a problem for you, but directly invoking the Constructor could invoke a problem for the Arduino cores using this API.

**Comment by jboynes** [comment]
Please can you clarify the potential problem you see here so I can fix this another way.

Are you concerned about the use of a delegating constructor like is used on line 52?

**Comment by aentinger** [comment]
>Are you concerned about the use of a delegating constructor like is used on line 52?

Yes.

Also, you are probably the only one that compiles the unit tests with clang. I'm reluctant to make this change to just accomodate a single user (sorry, but we've got to keep the bigger picture in mind, and clang is more exotic than plain old GCC).

**Comment by aentinger** [comment]
If you can fix your issue with `#pragmas`, that would also be a way. But no ctor delegation, sorry.

**Comment by jboynes** [comment]
The problem here isn't specific to clang but more to do with newer versions of the compilers. I get the same error with GCC-13

```
[  1%] Building CXX object CMakeFiles/test-ArduinoCore-API.dir/src/CanMsg/test_CanMsg.cpp.o
In file included from .../ArduinoCore-API/test/src/CanMsg/test_CanMsg.cpp:11:
.../ArduinoCore-API/test/../api/CanMsg.h: In copy constructor 'arduino::CanMsg::CanMsg(const arduino::CanMsg&)':
.../ArduinoCore-API/test/../api/CanMsg.h:58:36: error: the address of 'arduino::CanMsg::data' will never be NULL [-Werror=address]
   58 |     if (this->data_length && other.data)
      |                              ~~~~~~^~~~
```

The warning is correct, `other.data` can never be null because it's an array member and not a pointer, and warnings are treated as fatal errors.

So the simple fix here is just to remove the redundant check and I can update the PR to do that.

However, I'm unclear on the concern with delegating constructors: they are a C++11 feature which is the language version used by the API, and they are already used elsewhere in the code, for example on [line 52](https://github.com/arduino/ArduinoCore-API/blob/c48662794f48057459cf177ce424848ea28f2ef7/api/CanMsg.h#L52) of this file.

**Comment by jboynes** [comment]
Branch updated not to use constructor delegation. Should I create a new PR or would you reopen this one?

**Comment by aentinger** [comment]
>Should I create a new PR or would you reopen this one?

Just reopen this PR.

**Comment by jboynes** [comment]
> > Should I create a new PR or would you reopen this one?
> 
> Just reopen this PR.

I don't see the buttons for that. I'm guessing I don't have permission and so it would need to be reopened by committer.

**Comment by per1234** [comment]
It looks like it is impossible to reopen this pull request due to changes to the head branch:

image

So it will be necessary to open a new PR.

**Comment by jboynes** [comment]
Thanks for checking. I rebased and so had to force push, I guess that broke it.
Reopened as #224

**Pull request closed without merging**
